/**
 * MathMate.AI — Export Engine
 * 
 * Generates PDF and LaTeX files from solution data.
 * Runs entirely client-side with jsPDF.
 */

import { jsPDF } from 'jspdf';

/**
 * Export a solution as a downloadable PDF.
 */
export function exportToPdf(solution, inputExpression = '') {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('MathMate.AI — Solution', pageWidth / 2, y, { align: 'center' });
  y += 12;

  // Divider
  doc.setDrawColor(100, 100, 200);
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  y += 12;

  // Problem
  if (inputExpression) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Problem:', 20, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    const problemLines = doc.splitTextToSize(inputExpression, pageWidth - 40);
    doc.text(problemLines, 20, y);
    y += problemLines.length * 6 + 8;
  }

  // Answer
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Answer:', 20, y);
  y += 7;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  const answerText = solution.answer || solution.solution || 'N/A';
  const answerLines = doc.splitTextToSize(answerText, pageWidth - 40);
  doc.text(answerLines, 20, y);
  y += answerLines.length * 7 + 10;

  // LaTeX
  if (solution.latex) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('LaTeX:', 20, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont('courier', 'normal');
    const latexLines = doc.splitTextToSize(solution.latex, pageWidth - 40);
    doc.text(latexLines, 20, y);
    y += latexLines.length * 5 + 10;
  }

  // Steps
  if (solution.steps?.length > 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Step-by-Step Solution:', 20, y);
    y += 10;

    solution.steps.forEach((step, idx) => {
      // Check if we need a new page
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`Step ${step.step || idx + 1}:`, 20, y);
      y += 6;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);

      if (step.description) {
        // Clean description of inline math markers
        const cleanDesc = step.description.replace(/\$([^$]+)\$/g, '$1');
        const descLines = doc.splitTextToSize(cleanDesc, pageWidth - 45);
        doc.text(descLines, 25, y);
        y += descLines.length * 5 + 3;
      }

      if (step.latex) {
        doc.setFont('courier', 'normal');
        doc.setFontSize(10);
        const stepLatex = doc.splitTextToSize(step.latex, pageWidth - 45);
        doc.text(stepLatex, 25, y);
        y += stepLatex.length * 5 + 8;
      }
    });
  }

  // Footer
  y = Math.max(y + 10, 270);
  if (y > 280) { doc.addPage(); y = 270; }
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(150);
  doc.text('Generated by MathMate.AI — mathmate.ai', pageWidth / 2, 288, { align: 'center' });

  doc.save('mathmate-solution.pdf');
}

/**
 * Export a solution as a downloadable LaTeX file.
 */
export function exportToLatex(solution, inputExpression = '') {
  const latex = `\\documentclass{article}
\\usepackage{amsmath}
\\usepackage{amssymb}

\\title{MathMate.AI --- Solution}
\\date{\\today}

\\begin{document}
\\maketitle

\\section*{Problem}
\\[
${inputExpression || 'N/A'}
\\]

\\section*{Answer}
\\[
${solution.latex || solution.answer || solution.solution || 'N/A'}
\\]

${solution.steps?.length > 0 ? `\\section*{Step-by-Step Solution}
\\begin{enumerate}
${solution.steps.map((step, idx) => {
  const cleanDesc = (step.description || '').replace(/\$([^$]+)\$/g, '$$$1$$');
  return `  \\item ${cleanDesc}${step.latex ? `\n  \\[\n  ${step.latex}\n  \\]` : ''}`;
}).join('\n')}
\\end{enumerate}` : ''}

\\vfill
\\noindent\\textit{Generated by MathMate.AI}

\\end{document}
`;

  const blob = new Blob([latex], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'mathmate-solution.tex';
  a.click();
  URL.revokeObjectURL(url);
}
